version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - '8081:8080'
    command: ['go', 'run', 'main.go']
    restart: always
